version: '3.3'
services:
    gpu-jupyter:
        ports:
            - '8888:8888'
        volumes:
            - './:/home/jovyan/work'
        environment:
            - GRANT_SUDO=yes
            - JUPYTER_ENABLE_LAB=yes
        image: 'cschranz/gpu-jupyter:v1.4_cuda-11.2_ubuntu-20.04_python-only'
